// utils/categoryMapper.ts
export const categoryImageMap: Record<string, string> = {
  'Steam': 'steam',
  'Valorant': 'valorant',
  'Apple': 'apple',
  'Nintendo': 'nintendo_gift',
  'Apex Legends': 'ea_gift',
  'Games': 'games_pc_mac',
  'Xbox': 'xbox_gift',
  'Roblox': 'roblox_global',
  'Playstation': 'playstation_gift',
  'Blizzard': 'blizzard_gift',
  'Free Fire': 'games_pc_mac',
  'Mobile Legends': 'games_pc_mac',
  'Google Play': 'google_play_gift',
  'Twitch': 'social_network',
  'EA': 'ea_gift',
  'Meta Quest': 'games_pc_mac',
  'Battlefield': 'ea_gift',
  'Destiny': 'games_pc_mac',
  'Mafia': 'games_pc_mac',
  'Minecraft': 'games_pc_mac',
  'Plants vs. Zombies': 'ea_gift',
  'The Elder Scrolls': 'games_pc_mac',
  'Tom Clancy': 'games_pc_mac',
  'Warhammer': 'games_pc_mac',
  'Halo': 'xbox_games',
  'DOOM': 'games_pc_mac',
  'Indiana Jones': 'games_pc_mac',
  'Killing Floor': 'games_pc_mac',
  'Kingdom Come': 'games_pc_mac',
  'Lost in Random': 'games_pc_mac',
  'Ready or Not': 'games_pc_mac',
  'REMATCH': 'games_pc_mac',
  'Delta Force': 'games_pc_mac',
  'Doomsday': 'games_pc_mac',
  'Honor of Kings': 'games_pc_mac',
  'Lords Mobile': 'games_pc_mac',
  'Undawn': 'games_pc_mac',
  'The Sims': 'ea_gift',
  'Split Fiction': 'ea_gift',
  'Netflix': 'music_streaming',
  'Spotify': 'music_streaming',
  'Pubg Mobile': 'games_pc_mac',
  'Test': 'games_pc_mac'
};