// Маппинг категорий на их подкатегории
// Каждая подкатегория будет сопоставлена с категориями из API по имени

export interface Subcategory {
  name: string;
  // Будут использоваться для поиска соответствующей категории в API
  apiCategoryName?: string; // Точное имя категории в API для маппинга
}

export const SUBCATEGORIES: Record<string, Subcategory[]> = {
  'Amazon Gift Card': [
    { name: 'amazon.ae Gift Card' },
    { name: 'amazon.au Gift Card' },
    { name: 'amazon.com Gift Card' },
    { name: 'amazon.de Gift Card' },
    { name: 'amazon.fr Gift Card' },
    { name: 'amazon.in Voucher' },
    { name: 'amazon.it Gift Card' },
    { name: 'Amazon.jp Gift Card' },
    { name: 'amazon.nl Gift Card' },
    { name: 'amazon.sa Gift Card' },
    { name: 'amazon.tr Gift Card' },
    { name: 'amazon.uk gift card' },
  ],
  'Apple Gift Card': [
    { name: 'Apple Gift Card | AU' },
    { name: 'Apple Gift Card | BE' },
    { name: 'Apple Gift Card | BR' },
    { name: 'Apple Gift Card | FR' },
    { name: 'Apple Gift Card | IE' },
    { name: 'Apple Gift Card | IN' },
    { name: 'Apple Gift Card | IT' },
    { name: 'Apple Gift Card | JP' },
    { name: 'Apple Gift Card | PL' },
    { name: 'Apple Gift Card | PT' },
    { name: 'Apple Gift Card | RU' },
    { name: 'Apple Gift Card | TR' },
    { name: 'Apple Gift Card | USA' },
    { name: 'Apple | USA' },
    { name: 'Apple | TR' },
    { name: 'Apple | RU' },
  ],
  'Battle.net': [
    { name: 'Battle.net Gift Card | BR' },
    { name: 'Battle.net Gift Card | CA' },
    { name: 'Battle.net Gift Card | EU' },
    { name: 'Battle.net Gift Card | ID' },
    { name: 'Battle.net Gift Card | MX' },
    { name: 'Battle.net Gift Card | PL' },
    { name: 'Battle.net Gift Card | UK' },
    { name: 'Battle.net Gift Card | US' },
    { name: 'Blizzard Gift Card | US' },
    { name: 'Blizzard Gift Card | EU' },
    { name: 'Blizzard Gift Card | BR' },
  ],
  'EA App': [
    { name: 'Battlefield™ 2042' },
    { name: 'Battlefield™ 6' },
    { name: 'EA SPORTS FC™ 24' },
    { name: 'EA SPORTS FC™ 25 | GLOB | EA App' },
    { name: 'EA SPORTS FC™ 26' },
    { name: 'Split Fiction | GLOB | EA App' },
    { name: 'The Sims™ 4 | GLOB | EA App' },
  ],
  'EA Gift Card': [
    { name: 'EA Gift Card | EU' },
    { name: 'EA Gift Card | UK' },
    { name: 'EA Gift Card | US' },
  ],
  'Games | PC/Mac': [
    { name: 'Games | PC/Mac' },
  ],
  'Google Play Gift Card': [
    { name: 'Google Play Gift Card | BR' },
    { name: 'Google Play Gift Card | PL' },
    { name: 'Google Play Gift Code | DE' },
    { name: 'Google Play Gift Code | IN' },
    { name: 'Google Play Gift Code | JP' },
    { name: 'Google Play Gift Code | TR' },
    { name: 'Google Play Gift Code | US' },
  ],
  'League of Legends': [
    { name: 'League of Legends | AU' },
    { name: 'League of Legends | BR' },
    { name: 'League of Legends | EU' },
    { name: 'League of Legends | TR' },
    { name: 'League of Legends | UK' },
    { name: 'League of Legends | US' },
  ],
  'Mobile Games Donation': [
    { name: 'Delta Force Voucher | GLOB | Mobile Games' },
    { name: 'Doomsday: Last Survivors Gift Card | GLOB | Mobile Games' },
    { name: 'Free Fire' },
    { name: 'Honor of Kings Gift Card | GLOB | Mobile Games' },
    { name: 'Lords Mobile Gift Card | GLOB | Mobile Games' },
    { name: 'Mobile Legends: Bang Bang Voucher | GLOB | Mobile Games' },
    { name: 'Pubg Mobile Gift Card' },
    { name: 'Undawn gift card | GLOB | Mobile Games' },
  ],
  'Music & Streaming': [
    { name: 'Netflix Gift Card | AE' },
    { name: 'Netflix Gift Card | AU' },
    { name: 'Netflix Gift Card | BR' },
    { name: 'Netflix Gift Card | CO' },
    { name: 'Netflix Gift Card | EU' },
    { name: 'Netflix Gift Card | PL' },
    { name: 'Netflix Gift Card | SA' },
    { name: 'Netflix Gift Card | UK' },
    { name: 'Netflix Gift Card | US' },
    { name: 'Spotify Gift Card | IE' },
    { name: 'Spotify Gift Card | NL' },
    { name: 'Spotify Premium | AE' },
    { name: 'Spotify Premium | AT' },
    { name: 'Spotify Premium | AU' },
    { name: 'Spotify Premium | BE' },
    { name: 'Spotify Premium | BR' },
    { name: 'Spotify Premium | DE' },
    { name: 'Spotify Premium | DZ' },
    { name: 'Twitch Gift Card | US' },
  ],
  'Nintendo Gift Card': [
    { name: 'Nintendo Gift Card | BR' },
    { name: 'Nintendo Gift Card | EU' },
    { name: 'Nintendo Gift Card | JP' },
    { name: 'Nintendo Gift Card | PL' },
    { name: 'Nintendo Gift Card | UK' },
    { name: 'Nintendo | USD' },
  ],
  'Playstation Gift Card': [
    { name: 'PlayStation®Store Wallet | AE' },
    { name: 'PlayStation®Store Wallet | AT' },
    { name: 'PlayStation®Store Wallet | AU' },
    { name: 'PlayStation®Store Wallet | BE' },
    { name: 'PlayStation®Store Wallet | BH' },
    { name: 'PlayStation®Store Wallet | BR' },
    { name: 'PlayStation®Store Wallet | CA' },
    { name: 'PlayStation®Store Wallet | CZ' },
    { name: 'PlayStation®Store Wallet | DE' },
    { name: 'PlayStation®Store Wallet | ES' },
    { name: 'PlayStation®Store Wallet | FI' },
    { name: 'PlayStation®Store Wallet | FR' },
    { name: 'PlayStation®Store Wallet | GR' },
    { name: 'PlayStation®Store Wallet | HK' },
    { name: 'PlayStation®Store Wallet | HR' },
    { name: 'PlayStation®Store Wallet | HU' },
    { name: 'PlayStation®Store Wallet | ID' },
    { name: 'PlayStation®Store Wallet | IE' },
    { name: 'PlayStation®Store Wallet | INR' },
    { name: 'PlayStation®Store Wallet | IT' },
    { name: 'PlayStation®Store Wallet | KW' },
    { name: 'PlayStation®Store Wallet | LB' },
    { name: 'PlayStation®Store Wallet | LU' },
    { name: 'PlayStation®Store Wallet | MY' },
    { name: 'PlayStation®Store Wallet | NL' },
    { name: 'PlayStation®Store Wallet | NZ' },
    { name: 'PlayStation®Store Wallet | OM' },
    { name: 'PlayStation®Store Wallet | PLN' },
    { name: 'PlayStation®Store Wallet | PT' },
    { name: 'PlayStation®Store Wallet | QA' },
    { name: 'PlayStation®Store Wallet | RO' },
    { name: 'PlayStation®Store Wallet | SA' },
    { name: 'PlayStation®Store Wallet | SG' },
    { name: 'PlayStation®Store Wallet | SK' },
    { name: 'PlayStation®Store Wallet | TRY' },
    { name: 'PlayStation®Store Wallet | UK' },
    { name: 'PlayStation®Store Wallet | USA' },
    { name: 'PlayStation®Store Wallet | ZA' },
    { name: 'Playstation Gift Card | PLN' },
    { name: 'Playstation Gift Card | INR' },
    { name: 'Playstation Gift Card | USD' },
  ],
  'Razer Gold Gift Card': [
    { name: 'Razer Gold Gift Card' },
    { name: 'Razer Gold Gift Card | BR' },
    { name: 'Razer Gold Gift Card | EU' },
    { name: 'Razer Gold Gift Card | IN' },
    { name: 'Razer Gold Gift Card | MX' },
    { name: 'Razer Gold Gift Card | TR' },
  ],
  'Riot Cash Card': [
    { name: 'Riot Cash Card | AE' },
    { name: 'Riot Cash Card | BH' },
    { name: 'Riot Cash Card | BR' },
    { name: 'Riot Cash Card | EU' },
    { name: 'Riot Cash Card | KW' },
    { name: 'Riot Cash Card | LATAM' },
    { name: 'Riot Cash Card | SA' },
    { name: 'Riot Cash Card | TR' },
    { name: 'Riot Cash Card | UK' },
    { name: 'Riot Cash Card | US' },
  ],
  'Roblox': [
    { name: 'Roblox Gift Card | AE' },
    { name: 'Roblox Gift Card | AU' },
    { name: 'Roblox Gift Card | BR' },
    { name: 'Roblox Gift Card | EU' },
    { name: 'Roblox Gift Card | ID' },
    { name: 'Roblox Gift Card | PL' },
    { name: 'Roblox Gift Card | SA' },
    { name: 'Roblox Gift Card | UK' },
    { name: 'Roblox Gift Card | US' },
    { name: 'Roblox | Global' },
  ],
  'Rockstar Games': [
    { name: 'Bully: Scholarship Edition' },
    { name: 'Grand Theft Auto V' },
    { name: 'Max Payne 3' },
  ],
  'Social Network': [
    { name: 'Meta Quest gift card' },
    { name: 'Meta Quest gift card | EU' },
  ],
  'Steam Games': [
    { name: '7 Days to Die | GL' },
    { name: 'ARC Raiders | ROW' },
    { name: 'Atomic Heart | ROW' },
    { name: 'Beyond: Two Souls | GL' },
    { name: 'Borderlands 4 | GL' },
    { name: 'Clair Obscur: Expedition 33 | CIS' },
    { name: 'Crusader Kings III | GL' },
    { name: 'DARK SOULS™ II: Scholar of the First Sin | GL' },
    { name: 'Dead Cells | RU' },
    { name: 'Dead Island | GL' },
    { name: 'DEATHLOOP | ASIA' },
    { name: 'DEATHLOOP | CIS' },
    { name: 'DEATHLOOP | LATAM' },
    { name: 'DEATHLOOP | MENA' },
    { name: 'Destiny 2 | GLOB | Steam Games' },
    { name: 'Dishonored 2 | ASIA' },
    { name: 'Dishonored 2 | CIS' },
    { name: 'Dishonored 2 | GL' },
    { name: 'Dishonored 2 | LATAM' },
    { name: 'Dishonored 2 | MENA' },
    { name: 'Dishonored | ASIA' },
    { name: 'Dishonored | CIS' },
    { name: 'Dishonored®: Death of the Outsider™ | ASIA' },
    { name: 'Dishonored®: Death of the Outsider™ | CIS' },
    { name: 'Dishonored®: Death of the Outsider™ | CN' },
    { name: 'Dishonored®: Death of the Outsider™ | ID' },
    { name: 'Dishonored®: Death of the Outsider™ | IN' },
    { name: 'Dishonored®: Death of the Outsider™ | LATAM' },
    { name: 'Dishonored®: Death of the Outsider™ | MENA' },
    { name: 'Dishonored®: Death of the Outsider™ | PH' },
    { name: 'Dishonored | LATAM' },
    { name: 'Dishonored | MENA' },
    { name: 'DOOM Eternal | CIS | Steam Games' },
    { name: 'DOOM: The Dark Ages | ASIA' },
    { name: 'DOOM: The Dark Ages | CIS | Steam Games' },
    { name: 'DOOM: The Dark Ages | GL' },
    { name: 'DOOM: The Dark Ages | LATAM' },
    { name: 'DOOM: The Dark Ages | MENA' },
    { name: 'Dying Light 2 Stay Human | ROW' },
    { name: 'Dying Light | GL' },
    { name: 'Elden Ring Nightreign | RU' },
    { name: 'Euro Truck Simulator 2 | GL' },
    { name: 'Fallout 3 | ASIA' },
    { name: 'Fallout 3 | CIS | Steam Games' },
    { name: 'Fallout 3 | CN' },
    { name: 'Fallout 3 | ID' },
    { name: 'Fallout 3 | IN' },
    { name: 'Fallout 3 | LATAM' },
    { name: 'Fallout 3 | MENA' },
    { name: 'Fallout 3 | PH' },
    { name: 'Fallout 4 | ASIA' },
    { name: 'Fallout 4 | CIS | Steam Games' },
    { name: 'Fallout 4 | CN' },
    { name: 'Fallout 4 | ID' },
    { name: 'Fallout 4 | IN' },
    { name: 'Fallout 4 | LATAM' },
    { name: 'Fallout 4 | MENA' },
    { name: 'Fallout 76 | ASIA' },
    { name: 'Fallout 76 | CIS' },
    { name: 'Fallout 76 | LATAM' },
    { name: 'Fallout 76 | MENA' },
    { name: 'Fallout: New Vegas | CIS | Steam Games' },
    { name: 'Farming Simulator 25 | CIS' },
    { name: 'Farming Simulator 25 | ROW' },
    { name: 'FINAL FANTASY IX | GL' },
    { name: 'FINAL FANTASY TACTICS - The Ivalice Chronicles | GL' },
    { name: 'FINAL FANTASY X/X-2 HD Remaster | GL' },
    { name: 'For The King II | CIS' },
    { name: 'Ghost of Tsushima DIRECTOR\'S CUT | CIS' },
    { name: 'Ghostwire: Tokyo | ASIA' },
    { name: 'Ghostwire: Tokyo | CIS' },
    { name: 'Ghostwire: Tokyo | LATAM' },
    { name: 'Ghostwire: Tokyo | MENA' },
    { name: 'HELLDIVERS™ 2 | CIS' },
    { name: 'Hell is Us | ROW' },
    { name: 'Hell is Us | RU' },
    { name: 'Heretic + Hexen | CIS' },
    { name: 'Heretic + Hexen | LATAM' },
    { name: 'Heretic + Hexen | MENA' },
    { name: 'Hollow Knight: Silksong | GL' },
    { name: 'Indiana Jones and the Great Circle | ASIA' },
    { name: 'Indiana Jones and the Great Circle | CIS | Steam Games' },
    { name: 'Indiana Jones and the Great Circle | LATAM | GLOB | Steam Games' },
    { name: 'Indiana Jones and the Great Circle | MENA' },
    { name: 'Jump Space | GL' },
    { name: 'Just Cause 2 | GL' },
    { name: 'Just Cause 4 | GL' },
    { name: 'KARMA: The Dark World | CIS' },
    { name: 'Killing Floor 3 | ROW' },
    { name: 'Killing Floor 3 | ROW | GLOB | Steam Games' },
    { name: 'Killing Floor 3 | RU' },
    { name: 'Kingdom Come: Deliverance II | CIS | Steam Games' },
    { name: 'Kingdom Come: Deliverance II | LATAM | GLOB | Steam Games' },
    { name: 'Kingdom Come: Deliverance II | ROW | GLOB | Steam Games' },
    { name: 'Laika: Aged Through Blood | RU' },
    { name: 'LEGO® Bricktales | RU' },
    { name: 'Life is Strange 2 | GL' },
    { name: 'Life is Strange | ROW' },
    { name: 'Life is Strange: True Colors | GL' },
    { name: 'Lost in Random: The Eternal Die' },
    { name: 'Lost in Random: The Eternal Die | GLOB | Steam Games' },
    { name: 'Metro Awakening | GL' },
    { name: 'Metro Exodus | GL' },
    { name: 'Midnight Murder Club | CIS' },
    { name: 'Mount & Blade II: Bannerlord | GL' },
    { name: 'Old School RuneScape | GL' },
    { name: 'Outlast 2 | GL' },
    { name: 'PAC-MAN WORLD Re-PAC | GL' },
    { name: 'Planet of Lana | RU' },
    { name: 'Prey | ASIA' },
    { name: 'Prey | CIS' },
    { name: 'Prey | LATAM' },
    { name: 'Prey | MENA' },
    { name: 'PUBG: BATTLEGROUNDS | GL' },
    { name: 'Ready or Not | CIS | Steam Games' },
    { name: 'REMATCH | ROW | GLOB | Steam Games' },
    { name: 'Say No! More | RU' },
    { name: 'SILENT HILL f | ROW' },
    { name: 'Sonic Racing: CrossWorlds | GL' },
    { name: 'Squad | GL' },
    { name: 'Starfield | ASIA' },
    { name: 'Starfield | CIS' },
    { name: 'Starfield | GL' },
    { name: 'Starfield | LATAM' },
    { name: 'Starfield | MENA' },
    { name: 'SteamWorld Build | RU' },
    { name: 'SteamWorld Dig 2 | RU' },
    { name: 'SteamWorld Dig | RU' },
    { name: 'SteamWorld Heist II | RU' },
    { name: 'SteamWorld Heist | RU' },
    { name: 'SteamWorld Quest: Hand of Gilgamech | RU' },
    { name: 'Stronghold Crusader: Definitive Edition | GL' },
    { name: 'TEKKEN 7 | CIS' },
    { name: 'TEKKEN 7 | GL' },
    { name: 'TEKKEN 8 | ROW' },
    { name: 'Terraforming Mars | GL' },
    { name: 'The Elder Scrolls III: Morrowind® GOTY | ASIA' },
    { name: 'The Elder Scrolls III: Morrowind® GOTY | CIS' },
    { name: 'The Elder Scrolls III: Morrowind® GOTY | LATAM' },
    { name: 'The Elder Scrolls III: Morrowind® GOTY | MENA' },
    { name: 'The Elder Scrolls IV: Oblivion® GOTY | ASIA' },
    { name: 'The Elder Scrolls IV: Oblivion® GOTY | CIS' },
    { name: 'The Elder Scrolls IV: Oblivion® GOTY | LATAM' },
    { name: 'The Elder Scrolls IV: Oblivion® GOTY | MENA' },
    { name: 'The Elder Scrolls IV: Oblivion Remastered | ASIA' },
    { name: 'The Elder Scrolls IV: Oblivion Remastered | CIS | Steam Games' },
    { name: 'The Elder Scrolls IV: Oblivion Remastered | LATAM' },
    { name: 'The Elder Scrolls IV: Oblivion Remastered | MENA' },
    { name: 'The Elder Scrolls Online | ASIA' },
    { name: 'The Elder Scrolls Online | CIS' },
    { name: 'The Elder Scrolls Online | LATAM' },
    { name: 'The Elder Scrolls Online | MENA' },
    { name: 'The Elder Scrolls V: Skyrim | ASIA' },
    { name: 'The Elder Scrolls V: Skyrim | CIS' },
    { name: 'The Elder Scrolls V: Skyrim | CIS | Steam Games' },
    { name: 'The Elder Scrolls V: Skyrim | GL' },
    { name: 'The Elder Scrolls V: Skyrim | LATAM' },
    { name: 'The Elder Scrolls V: Skyrim | MENA' },
    { name: 'The Evil Within 2 | ASIA' },
    { name: 'The Evil Within 2 | CIS' },
    { name: 'The Evil Within 2 | LATAM' },
    { name: 'The Evil Within 2 | MENA' },
    { name: 'The First Berserker: Khazan | ROW' },
    { name: 'The Forever Winter | CIS' },
    { name: 'The Gunk | RU' },
    { name: 'The Last of Us™ Part II Remastered | CIS' },
    { name: 'The Last of Us™ Part II Remastered | ROW' },
    { name: 'The Last of Us™ Part I | ROW' },
    { name: 'The Lord of the Rings: Gollum™ | RU' },
    { name: 'The Lord of the Rings: Return to Moria™ | GL' },
    { name: 'Train Sim World® 6 | GL' },
    { name: 'TT Isle of Man: Ride on the Edge 2 | GL' },
    { name: 'Vampire: The Masquerade - Swansong | GL' },
    { name: 'Vampire: The Masquerade - Swansong | RU' },
    { name: 'Viewfinder | RU' },
    { name: 'VOID/BREAKER | AE' },
    { name: 'VOID/BREAKER | RU' },
    { name: 'V Rising | ROW' },
    { name: 'V Rising | RU' },
    { name: 'Warhammer 40,000: Dawn of War Definitive Edition | GL' },
    { name: 'Warhammer 40,000: Rogue Trader | CIS' },
    { name: 'Warhammer 40,000: Rogue Trader | GL' },
    { name: 'Warhammer 40,000: Rogue Trader | GLOB | Steam Games' },
    { name: 'Warhammer 40,000: Space Marine 2 | GL' },
    { name: 'Warhammer 40,000: Space Marine 2 | GLOB | Steam Games' },
    { name: 'Wavetale | RU' },
    { name: 'White Shadows | RU' },
    { name: 'Wolfenstein II: The New Colossus | ASIA' },
    { name: 'Wolfenstein II: The New Colossus | CIS' },
    { name: 'Wolfenstein II: The New Colossus | LATAM' },
    { name: 'Wolfenstein II: The New Colossus | MENA' },
    { name: 'Wolfenstein: The New Order | ASIA' },
    { name: 'Wolfenstein: The New Order | CIS' },
    { name: 'Wolfenstein: The New Order | LATAM' },
    { name: 'Wolfenstein: The New Order | MENA' },
    { name: 'Wolfenstein: The Old Blood | ASIA' },
    { name: 'Wolfenstein: The Old Blood | CIS' },
    { name: 'Wolfenstein: The Old Blood | LATAM' },
    { name: 'Wolfenstein: The Old Blood | MENA' },
  ],
  'Steam Wallet': [
    { name: 'Steam CIS TopUp' },
    { name: 'Steam Wallet Code | AE' },
    { name: 'Steam Wallet Code | AR' },
    { name: 'Steam Wallet Code | BH' },
    { name: 'Steam Wallet Code | EU' },
    { name: 'Steam Wallet Code | HK' },
    { name: 'Steam Wallet Code | ID' },
    { name: 'Steam Wallet Code | IN' },
    { name: 'Steam Wallet Code | KR' },
    { name: 'Steam Wallet Code | KW' },
    { name: 'Steam Wallet Code | MX' },
    { name: 'Steam Wallet Code | MY' },
    { name: 'Steam Wallet Code | NG' },
    { name: 'Steam Wallet Code | OM' },
    { name: 'Steam Wallet Code | PH' },
    { name: 'Steam Wallet Code | PL' },
    { name: 'Steam Wallet Code | QA' },
    { name: 'Steam Wallet Code | SA' },
    { name: 'Steam Wallet Code | SG' },
    { name: 'Steam Wallet Code | TH' },
    { name: 'Steam Wallet Code | TR' },
    { name: 'Steam Wallet Code | TW' },
    { name: 'Steam Wallet Code | UK' },
    { name: 'Steam Wallet Code | USA' },
    { name: 'Steam Wallet Code | VN' },
    { name: 'Steam Wallet Code | ZA' },
  ],
  'Valorant': [
    { name: 'Valorant | RU' },
    { name: 'Valorant | TR' },
  ],
  'Xbox Games': [
    { name: 'Apex Legends | Xbox' },
    { name: 'Battlefield™ 2042 | GLOB | Xbox Games' },
    { name: 'Destiny 2 | GLOB | Xbox Games' },
    { name: 'EA SPORTS FC™ 25 | GLOB | Xbox Games' },
    { name: 'Fallout 76 | GLOB | Xbox Games' },
    { name: 'Halo Infinite | GLOB | Xbox Games' },
    { name: 'Mafia: The Old Country | GLOB | Xbox Games' },
    { name: 'Minecraft | GLOB | Xbox Games' },
    { name: 'Plants vs. Zombies: Battle for Neighborville™ | GLOB | Xbox Games' },
    { name: 'The Elder Scrolls IV: Oblivion Remastered | GLOB | Xbox Games' },
    { name: 'Tom Clancy\'s Rainbow Six® Extraction | GLOB | Xbox Games' },
    { name: 'Tom Clancy\'s Rainbow Six® Siege X | GLOB | Xbox Games' },
    { name: 'Tom Clancy\'s The Division 2 | GLOB | Xbox Games' },
    { name: 'Warhammer 40,000: Space Marine 2 | GLOB | Xbox Games' },
  ],
  'Xbox Gift Card': [
    { name: 'Xbox Gift Card | BR' },
    { name: 'Xbox Gift Card | CO' },
    { name: 'Xbox Gift Card | HU' },
    { name: 'Xbox Gift Card | PL' },
    { name: 'Xbox Gift Card | TRY' },
    { name: 'Xbox Gift Card | US' },
    { name: 'Xbox Gift Card | ZAR' },
  ],
  'Xbox Subscriptions': [
    { name: 'Xbox Game Pass Core | IN' },
    { name: 'Xbox Game Pass For PC | IN' },
    { name: 'Xbox Game Pass Ultimate | IN' },
  ],
};

// Функция для получения подкатегорий категории
export const getSubcategories = (categoryName: string): Subcategory[] => {
  return SUBCATEGORIES[categoryName] || [];
};

// Функция для проверки, есть ли у категории подкатегории
export const hasSubcategories = (categoryName: string): boolean => {
  const subcategories = SUBCATEGORIES[categoryName];
  return subcategories !== undefined && subcategories.length > 0;
};

// Функция для поиска категории API по имени подкатегории
// Используется для маппинга подкатегории к category_id из API
export const findApiCategoryByName = (
  apiCategories: Array<{ category_id: number; category_name: string }>,
  subcategoryName: string
): number | null => {
  // Сначала фильтруем категории с валидным ID (> 0)
  const validCategories = apiCategories.filter(cat => cat.category_id > 0);

  // Нормализуем имена для сравнения (убираем лишние пробелы, приводим к нижнему регистру)
  const normalizedSubcategoryName = subcategoryName.trim().toLowerCase();
  
  // Сначала пытаемся найти точное совпадение
  const exactMatch = validCategories.find(
    cat => cat.category_name.trim().toLowerCase() === normalizedSubcategoryName
  );
  
  if (exactMatch) {
    return exactMatch.category_id;
  }
  
  // Если точного совпадения нет, пытаемся найти частичное совпадение
  // (на случай, если названия немного отличаются)
  const partialMatch = validCategories.find(
    cat => {
      const normalizedApiName = cat.category_name.trim().toLowerCase();
      // Проверяем, содержит ли имя API категории имя подкатегории или наоборот
      return normalizedApiName.includes(normalizedSubcategoryName) || 
             normalizedSubcategoryName.includes(normalizedApiName);
    }
  );
  
  if (partialMatch) {
    return partialMatch.category_id;
  }
  
  return null;
};
